Update openwrt-ci.yml

diff --git a/.github/workflows/openwrt-ci.yml b/.github/workflows/openwrt-ci.yml
--- a/.github/workflows/openwrt-ci.yml
+++ b/.github/workflows/openwrt-ci.yml
@@ -41,6 +41,13 @@ jobs:
       - name: Checkout OpenWrt
         uses: actions/checkout@v3
 
+     - name: Check for .config file
+        run: |
+          if [ ! -f .config ]; then
+            echo "Error: No .config file found in the root directory."
+            exit 1
+          fi
+
       - name: Update feeds
         run: |
           sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
